root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/myserver"
  cmd = "templ generate && go build -o ./tmp/myserver ./cmd/myserver/"
  delay = 1000
  exclude_dir = ["tmp", "node_modules", "vendor"]
  exclude_regex = ["_templ.go$", "_test.go$"]
  include_ext = ["go", "templ", "yaml", "yml"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
